# Generated by Django 4.0.3 on 2022-07-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='title',
            new_name='titlee',
        ),
    ]
