# Generated by Django 4.0.3 on 2022-07-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_title_tweets_titlee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweets',
            new_name='Tweet',
        ),
    ]
