# Generated by Django 4.0.3 on 2022-07-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tweets_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tag',
            field=models.CharField(default='education', max_length=20),
        ),
    ]
