# Generated by Django 4.0.3 on 2022-07-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tweet_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
